{% set name = "verticapy" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/verticapy-{{ version }}.tar.gz
  sha256: 1707eb8d83bd2ec959edc66af1e8b94e6f2cae973afdb894ac6aa0da6e905d81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - python <3.9
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - python <3.9
    - scipy
    - vertica-python
    - python-dateutil
    - python-graphviz
    - requests-kerberos
    - tqdm
    - pandas
    - python-highcharts

test:
  imports:
    - verticapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vertica/VerticaPy
  summary: VerticaPy simplifies data exploration, data cleaning and machine learning in Vertica.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
    - oualib
    - afard
    - condacircus
